//! Monomorphic stage dispatch for pipeline parsing.
//!
//! [`ParseDispatch`] replaces the HRTB-based `SupportsStageDispatchMut` path
//! for pipeline text parsing. Each stage enum variant dispatches to a concrete
//! dialect parser with concrete lifetimes, which avoids the E0275 trait-solver
//! overflow that occurs when `Block`/`Region`-containing types use `#[wraps]`.
//!
//! For single-dialect pipelines (`Pipeline<StageInfo<L>>`), a blanket impl is
//! provided so no derive macro is needed.
//!
//! For multi-dialect stage enums, use `#[derive(ParseDispatch)]` from
//! `kirin-derive-ir`.

use kirin_ir::{CompileStage, Dialect, StageInfo, StageMeta};

use crate::{HasParser, HasParserEmitIR};

use super::error::FunctionParseError;
use super::parse_text::{FirstPassCtx, FirstPassDispatchResult, SecondPassCtx};
pub use super::parse_text::{first_pass_concrete, second_pass_concrete};

/// Monomorphic stage dispatch for pipeline parsing.
///
/// Generated by `#[derive(ParseDispatch)]` on stage enums. Each variant
/// dispatches to the concrete dialect's parser with concrete lifetimes,
/// eliminating all HRTB bounds from the pipeline parsing path.
///
/// For single-dialect pipelines (`Pipeline<StageInfo<L>>`), a blanket impl
/// handles dispatch automatically.
pub trait ParseDispatch: StageMeta {
    fn dispatch_first_pass(
        &mut self,
        stage_id: CompileStage,
        ctx: &mut FirstPassCtx<'_>,
    ) -> Result<Option<FirstPassDispatchResult>, FunctionParseError>;

    fn dispatch_second_pass(
        &mut self,
        stage_id: CompileStage,
        ctx: &mut SecondPassCtx<'_>,
    ) -> Result<Option<usize>, FunctionParseError>;
}

/// Blanket impl for single-dialect pipelines (`Pipeline<StageInfo<L>>`).
///
/// The `for<'t>` bounds here are safe because `L` is a concrete (fixed) type,
/// not a type parameter being resolved recursively through the trait solver.
impl<L> ParseDispatch for StageInfo<L>
where
    L: Dialect,
    L::Type: kirin_ir::Placeholder,
    for<'t> L: HasParserEmitIR<'t>,
    for<'t> L::Type: HasParser<'t, Output = L::Type>,
{
    fn dispatch_first_pass(
        &mut self,
        stage_id: CompileStage,
        ctx: &mut FirstPassCtx<'_>,
    ) -> Result<Option<FirstPassDispatchResult>, FunctionParseError> {
        first_pass_concrete::<L>(self, stage_id, ctx).map(Some)
    }

    fn dispatch_second_pass(
        &mut self,
        stage_id: CompileStage,
        ctx: &mut SecondPassCtx<'_>,
    ) -> Result<Option<usize>, FunctionParseError> {
        second_pass_concrete::<L>(self, stage_id, ctx).map(Some)
    }
}
