use std::marker::PhantomData;

use kirin_ir::{
    Block, CompileStage, Dialect, GetInfo, HasStageInfo, SSAValue, StageInfo, Statement,
};

use crate::concrete::ConcreteDomain;
use crate::core::Core;
use crate::env::{Env, Interpretable};
use crate::error::InterpreterError;
use crate::lift::{Lift, Project};

/// Cursor execution trait.
///
/// Each cursor drives one unit of work: a block traversal, an SCF body phase,
/// etc. Returns `E::Effect` — the language-level effect — which the driver loop
/// dispatches via `Project<Core<V, E::Cursor>>`.
///
/// Implementations are dialect-specific. The composed language cursor type
/// (e.g. `MyLangCursor<V>`) implements `Execute<E>` by dispatching to each
/// variant's cursor. This dispatch impl is generated by `#[derive(ComposedCursor)]`
/// but written manually until the derive is implemented.
pub trait Execute<E: Env> {
    fn execute(&mut self, env: &mut E) -> Result<E::Effect, E::Error>;
}

/// Linear cursor over statements in a single block.
///
/// Handles `Core::Advance` and `Core::Jump` internally (loops without returning),
/// so the driver loop only ever sees Push / Pop / Yield / Return / Call effects.
///
/// `L` is the dialect whose ops are interpreted. For a composed language, `L`
/// is the full language type, not a single dialect.
pub struct BlockCursor<V, L: Dialect> {
    block: Block,
    stage_id: CompileStage,
    current: Option<Statement>,
    init_args: Option<Vec<V>>,
    _phantom: PhantomData<L>,
}

impl<V, L: Dialect> BlockCursor<V, L> {
    pub fn new(block: Block, stage_id: CompileStage, args: Vec<V>) -> Self {
        Self {
            block,
            stage_id,
            current: None,
            init_args: Some(args),
            _phantom: PhantomData,
        }
    }

    pub fn block(&self) -> Block {
        self.block
    }

    pub fn stage_id(&self) -> CompileStage {
        self.stage_id
    }

    fn advance_stmt(&mut self, stage: &StageInfo<L>) {
        let Some(current) = self.current else {
            return;
        };
        self.current = if Some(current) == self.block.last_statement(stage) {
            None
        } else {
            (*current.next(stage)).or_else(|| self.block.terminator(stage))
        };
    }
}

impl<E, L, V> Execute<E> for BlockCursor<V, L>
where
    V: Clone,
    L: Dialect + Interpretable<E, DialectEffect = E::Effect>,
    E: ConcreteDomain<Value = V>,
    // These two bounds follow from E: ConcreteDomain but must be restated here
    // because Rust does not automatically propagate trait where-clause bounds to
    // generic users of the trait.
    E::Effect: Lift<Core<V, E::Cursor>> + Project<Core<V, E::Cursor>>,
    E::StageContainer: HasStageInfo<L>,
    E::Error: From<InterpreterError>,
{
    fn execute(&mut self, env: &mut E) -> Result<E::Effect, E::Error> {
        // First call: bind block arguments and set the initial statement pointer.
        if let Some(args) = self.init_args.take() {
            let (ssa_keys, expected) = {
                let stage = env
                    .stage_info_for::<L>(self.stage_id)
                    .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                let block_info = self.block.expect_info(stage);
                let expected = block_info.arguments.len();
                let ssa_keys: Vec<SSAValue> = block_info
                    .arguments
                    .iter()
                    .map(|ba| SSAValue::from(*ba))
                    .collect();
                (ssa_keys, expected)
            };
            if args.len() != expected {
                return Err(E::Error::from(InterpreterError::ArityMismatch {
                    expected,
                    got: args.len(),
                }));
            }
            for (ssa, val) in ssa_keys.into_iter().zip(args.iter()) {
                env.write_ssa(ssa, val.clone())?;
            }
            let stage = env
                .stage_info_for::<L>(self.stage_id)
                .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
            self.current = self.block.first_statement(stage);
        }

        loop {
            let Some(stmt) = self.current else {
                return Err(E::Error::from(InterpreterError::NoCurrent));
            };

            // Clone the definition to release the stage borrow before calling interpret.
            let definition: L = {
                let stage = env
                    .stage_info_for::<L>(self.stage_id)
                    .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                stmt.definition(stage).clone()
            };

            let effect = definition.interpret(env)?;

            // Advance and Jump are handled here; everything else goes to the driver loop.
            match Project::<Core<V, E::Cursor>>::project(effect) {
                Ok(Core::Advance) => {
                    let stage = env
                        .stage_info_for::<L>(self.stage_id)
                        .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                    self.advance_stmt(stage);
                }
                Ok(Core::Jump(block, jump_args)) => {
                    let (ssa_keys, first_stmt) = {
                        let stage = env
                            .stage_info_for::<L>(self.stage_id)
                            .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                        let block_info = block.expect_info(stage);
                        let expected = block_info.arguments.len();
                        if jump_args.len() != expected {
                            return Err(E::Error::from(InterpreterError::ArityMismatch {
                                expected,
                                got: jump_args.len(),
                            }));
                        }
                        let ssa_keys: Vec<SSAValue> = block_info
                            .arguments
                            .iter()
                            .map(|ba| SSAValue::from(*ba))
                            .collect();
                        let first_stmt = block.first_statement(stage);
                        (ssa_keys, first_stmt)
                    };
                    self.block = block;
                    self.current = first_stmt;
                    for (ssa, val) in ssa_keys.into_iter().zip(jump_args.iter()) {
                        env.write_ssa(ssa, val.clone())?;
                    }
                }
                Ok(other_core) => {
                    {
                        let stage = env
                            .stage_info_for::<L>(self.stage_id)
                            .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                        self.advance_stmt(stage);
                    }
                    return Ok(E::Effect::lift(other_core));
                }
                Err(dialect_effect) => {
                    {
                        let stage = env
                            .stage_info_for::<L>(self.stage_id)
                            .ok_or_else(|| E::Error::from(InterpreterError::MissingEntry))?;
                        self.advance_stmt(stage);
                    }
                    return Ok(dialect_effect);
                }
            }
        }
    }
}
