site_name: kirin-toolchain

repo_name: kirin-toolchain
repo_url: https://github.com/QuEraComputing/kirin

# Page tree
nav:
  - Home:
      - index.md
      - Installation: install.md
      - Declarations: def.md
      - Compiler 101: 101.md
  - API Reference:
    - IR:
      - reference/kirin/ir/index.md
      - Nodes: reference/kirin/ir/nodes/
      - SSA values: reference/kirin/ir/ssa.md
      - Attributes: reference/kirin/ir/attrs.md
      - Traits: reference/kirin/ir/traits.md
      - Dialect: reference/kirin/ir/dialect.md
      - Dialect Group: reference/kirin/ir/group.md
      - Method: reference/kirin/ir/method.md
    - Interpreter: reference/kirin/interp/
    - Python Lowering: reference/kirin/lowering/
    - Analysis:
      - reference/kirin/analysis/index.md
      - Dataflow: reference/kirin/analysis/dataflow/
      - CFG: reference/kirin/analysis/cfg.md
    - Rewrite:
      - Generic: reference/kirin/rewrite/
      - Rules: reference/kirin/rules/
    - Method Pass: reference/kirin/passes/
    - Code Generation: reference/kirin/codegen/
    - Pretty Printing: reference/kirin/print/
    - IR declaration: reference/kirin/decl/
    - Exceptions: reference/kirin/exceptions.md
    - Data Structures:
      - Lattice: reference/kirin/lattice.md
      - Graph: reference/kirin/graph.md
      - IdTable: reference/kirin/idtable.md
      - Source: reference/kirin/source.md
      - WorkList: reference/kirin/worklist.md
    - Prelude: reference/kirin/prelude.md

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_if_no_docstring: false
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - search:
      separator: '[\s\-,:!=\[\: )"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - minify:
      minify_html: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
