//! Centralized where-clause predicate generation for derive macro implementations.
//!
//! [`ImplBounds`] pre-computes what bounds are needed from the IR input, then
//! provides parameterized methods to generate predicates with specific lifetime
//! and language tokens. This eliminates the duplication where every generator
//! independently collects value types, wrapper types, and result-field flags
//! before building nearly identical where-clause predicates.

use proc_macro2::TokenStream;

use crate::ChumskyLayout;
use crate::codegen::{
    GeneratorConfig, collect_all_value_types_needing_bounds, collect_wrapper_types,
};

/// Pre-computed information about what where-clause predicates are needed for
/// trait impls generated by `#[derive(HasParser)]`.
///
/// Constructed once per derive invocation and shared across all generators.
/// Methods are parameterized by lifetime (`'t` or `'tokens`) and language
/// token (`Language`, `__Language`, or a concrete type), so the same collected
/// data generates predicates for different impl contexts.
pub(crate) struct ImplBounds {
    crate_path: syn::Path,
    ir_path: syn::Path,
    ir_type: syn::Path,
    value_types: Vec<syn::Type>,
    wrapper_types: Vec<syn::Type>,
    ir_type_is_param: bool,
}

impl ImplBounds {
    /// Creates bounds context from IR input and generator config.
    pub fn from_input(
        ir_input: &kirin_derive_toolkit::ir::Input<ChumskyLayout>,
        config: &GeneratorConfig,
    ) -> Self {
        let value_types = collect_all_value_types_needing_bounds(ir_input);
        let wrapper_types = collect_wrapper_types(ir_input);
        let ir_type_is_param = {
            let ir_type = &config.ir_type;
            ir_type.segments.len() == 1
                && ir_input
                    .generics
                    .type_params()
                    .any(|tp| tp.ident == ir_type.segments[0].ident)
        };

        Self {
            crate_path: config.crate_path.clone(),
            ir_path: config.ir_path.clone(),
            ir_type: config.ir_type.clone(),
            value_types,
            wrapper_types,
            ir_type_is_param,
        }
    }

    // --- Accessors ---

    pub fn has_wrappers(&self) -> bool {
        !self.wrapper_types.is_empty()
    }

    /// True when any statement has `ResultValue` fields.
    ///
    /// Note: `Placeholder` is no longer needed for `ResultValue::emit` since
    /// forward refs now use `ty: None`. This returns false unconditionally.
    /// The builder path (Dialect derive) still uses `Placeholder` for auto-placeholder,
    /// but that's handled separately in `kirin-derive-toolkit`.
    pub fn needs_placeholder(&self) -> bool {
        false
    }

    /// True when `Placeholder` is needed considering wrappers too.
    ///
    /// Returns false — `Placeholder` is no longer needed in the EmitIR path.
    pub fn needs_placeholder_with_wrappers(&self) -> bool {
        false
    }

    // --- IR type predicates ---

    /// `IrType: HasParser<'lt, Output = IrType> + 'lt`
    ///
    /// The `Output = IrType` constraint is required for Signature fields
    /// (which store `Signature<T>` directly rather than `Signature<T::Output>`)
    /// and is always satisfied by type lattices.
    pub fn ir_type_has_parser(&self, lt: &syn::Lifetime) -> syn::WherePredicate {
        let ir_type = &self.ir_type;
        let crate_path = &self.crate_path;
        syn::parse_quote! { #ir_type: #crate_path::HasParser<#lt, Output = #ir_type> + #lt }
    }

    /// `<IrType as HasParser<'lt>>::Output: EmitIR<Lang, Output = <Lang as Dialect>::Type>`
    pub fn ir_type_emit_ir(
        &self,
        lt: &syn::Lifetime,
        language: &TokenStream,
    ) -> syn::WherePredicate {
        let ir_type = &self.ir_type;
        let crate_path = &self.crate_path;
        let ir_path = &self.ir_path;
        syn::parse_quote! {
            <#ir_type as #crate_path::HasParser<#lt>>::Output:
                #crate_path::EmitIR<#language, Output = <#language as #ir_path::Dialect>::Type>
        }
    }

    // --- Value type predicates ---

    /// `Ty: HasParser<'lt> + 'lt` for each value type.
    pub fn value_types_has_parser(&self, lt: &syn::Lifetime) -> Vec<syn::WherePredicate> {
        let crate_path = &self.crate_path;
        self.value_types
            .iter()
            .map(|ty| syn::parse_quote! { #ty: #crate_path::HasParser<#lt> + #lt })
            .collect()
    }

    /// Both `HasParser` and `EmitIR` predicates for each value type.
    pub fn value_types_all(
        &self,
        lt: &syn::Lifetime,
        language: &TokenStream,
    ) -> Vec<syn::WherePredicate> {
        let crate_path = &self.crate_path;
        self.value_types
            .iter()
            .flat_map(|ty| {
                [
                    syn::parse_quote! { #ty: #crate_path::HasParser<#lt> + #lt },
                    syn::parse_quote! {
                        <#ty as #crate_path::HasParser<#lt>>::Output:
                            #crate_path::EmitIR<#language, Output = #ty>
                    },
                ]
            })
            .collect()
    }

    // --- Wrapper type predicates ---

    /// `Ty: HasDialectParser<'lt>` for each wrapper type.
    pub fn wrappers_has_dialect_parser(&self, lt: &syn::Lifetime) -> Vec<syn::WherePredicate> {
        let crate_path = &self.crate_path;
        self.wrapper_types
            .iter()
            .map(|ty| syn::parse_quote! { #ty: #crate_path::HasDialectParser<#lt> })
            .collect()
    }

    /// `Ty: HasDialectEmitIR<'lt, Lang, LangOutput>` for each wrapper type.
    pub fn wrappers_emit_ir(
        &self,
        lt: &syn::Lifetime,
        language: &TokenStream,
        lang_output: &TokenStream,
    ) -> Vec<syn::WherePredicate> {
        let crate_path = &self.crate_path;
        self.wrapper_types
            .iter()
            .map(|ty| {
                syn::parse_quote! {
                    #ty: #crate_path::HasDialectEmitIR<#lt, #language, #lang_output>
                }
            })
            .collect()
    }

    // --- Conditional predicates ---

    /// `Lang: Dialect<Type = IrType>` — only if `ir_type` is a type parameter.
    pub fn dialect_type_bound(&self, language: &TokenStream) -> Option<syn::WherePredicate> {
        if self.ir_type_is_param {
            let ir_type = &self.ir_type;
            let ir_path = &self.ir_path;
            Some(syn::parse_quote! { #language: #ir_path::Dialect<Type = #ir_type> })
        } else {
            None
        }
    }

    /// Placeholder predicates needed for the emit impl.
    ///
    /// Returns `<Lang as Dialect>::Type: Placeholder`. When the IR type is a
    /// type parameter (e.g. `T`), also returns `T: Placeholder` directly
    /// so the compiler can resolve the bound without normalization.
    pub fn placeholder_predicates(&self, language: &TokenStream) -> Vec<syn::WherePredicate> {
        let ir_path = &self.ir_path;
        let mut preds = vec![
            syn::parse_quote! { <#language as #ir_path::Dialect>::Type: #ir_path::Placeholder },
        ];
        if self.ir_type_is_param {
            let ir_type = &self.ir_type;
            preds.push(syn::parse_quote! { #ir_type: #ir_path::Placeholder });
        }
        preds
    }
}

/// Creates a `WhereClause` from `combine_where_clauses`, defaulting to an
/// empty clause when both inputs are `None`.
///
/// Eliminates the repeated `match combined { Some(wc) => wc, None => empty }`.
pub(crate) fn init_where_clause(
    base: Option<&syn::WhereClause>,
    extra: Option<&syn::WhereClause>,
) -> syn::WhereClause {
    kirin_derive_toolkit::codegen::combine_where_clauses(base, extra).unwrap_or_else(|| {
        syn::WhereClause {
            where_token: syn::token::Where::default(),
            predicates: syn::punctuated::Punctuated::new(),
        }
    })
}

/// Extension trait for pushing optional predicates into a where clause.
pub(crate) trait WhereClauseExt {
    fn push_opt(&mut self, pred: Option<syn::WherePredicate>);
}

impl WhereClauseExt for syn::WhereClause {
    fn push_opt(&mut self, pred: Option<syn::WherePredicate>) {
        if let Some(p) = pred {
            self.predicates.push(p);
        }
    }
}
