from kirin.analysis.dataflow.lattice.const import (
    Const,
    NotConst,
    PartialLambda,
    PartialTuple,
    Unknown,
)

class _ConstLattice:
    def is_subseteq_Const(self, other: Const) -> bool: ...
    def is_subseteq_NotConst(self, other: NotConst) -> bool: ...
    def is_subseteq_Unknown(self, other: Unknown) -> bool: ...
    def is_subseteq_PartialTuple(self, other: PartialTuple) -> bool: ...
    def is_subseteq_PartialLambda(self, other: PartialLambda) -> bool: ...
