use kirin::prelude::*;

/// A lambda expression that captures variables from the enclosing scope.
///
/// # E0275 Limitation
///
/// `Lambda` contains a `Region` field, which causes trait solver overflow
/// (E0275) when composed via `#[wraps]` + `HasParser`. The recursive AST
/// types generated by the parser derive exceed the default recursion limit.
///
/// **Workaround**: Inline the `Lambda` fields directly into the parent
/// language enum instead of wrapping the struct with `#[wraps]`. See
/// `example/simple.rs` for a working example.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Dialect, HasParser, PrettyPrint)]
#[kirin(fn, type = T)]
#[chumsky(format = "{res:name} = {.lambda} {name} captures({captures}) {body} -> {res:type}")]
pub struct Lambda<T: CompileTimeValue> {
    name: Symbol,
    captures: Vec<SSAValue>,
    body: Region,
    res: ResultValue,
    #[kirin(default)]
    marker: std::marker::PhantomData<T>,
}
