use kirin_ir::{Dialect, Signature, StageInfo, Statement};

use super::{EmitContext, EmitError, EmitIR, HasParser, ParseError, parse_ast};

/// Error type for combined parse-and-emit operations.
///
/// Distinguishes between errors that occurred during parsing (chumsky-level
/// syntax errors) and errors that occurred during IR emission (e.g., undefined
/// SSA values or blocks).
#[derive(Debug, Clone)]
pub enum ChumskyError {
    /// One or more syntax errors from the chumsky parser.
    Parse(Vec<ParseError>),
    /// An error during IR emission from a successfully parsed AST.
    Emit(EmitError),
}

impl std::fmt::Display for ChumskyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ChumskyError::Parse(errors) => {
                for (i, e) in errors.iter().enumerate() {
                    if i > 0 {
                        write!(f, "; ")?;
                    }
                    write!(f, "{e}")?;
                }
                Ok(())
            }
            ChumskyError::Emit(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for ChumskyError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ChumskyError::Emit(e) => Some(e),
            ChumskyError::Parse(_) => None,
        }
    }
}

impl From<Vec<ParseError>> for ChumskyError {
    fn from(errors: Vec<ParseError>) -> Self {
        ChumskyError::Parse(errors)
    }
}

impl From<EmitError> for ChumskyError {
    fn from(error: EmitError) -> Self {
        ChumskyError::Emit(error)
    }
}

/// A dialect that can parse text and emit IR in one step.
///
/// This replaces the old `HasParserEmitIR` + `HasDialectEmitIR` witness traits.
/// Downstream developers implement this trait to plug into `ParseStatementText`
/// and `ParsePipelineText` without needing `#[derive(HasParser)]`.
///
/// # Three implementation paths
///
/// 1. **Derive**: `#[derive(HasParser)]` generates this automatically.
/// 2. **Marker**: Implement `SimpleParseEmit` for non-recursive dialects
///    (no `Block`/`Region` fields) to get a blanket impl for free.
/// 3. **Manual**: Implement directly for full control over parse+emit.
pub trait ParseEmit<L: Dialect = Self>: Dialect {
    /// Parse input text and emit a single IR statement.
    fn parse_and_emit(input: &str, ctx: &mut EmitContext<'_, L>)
    -> Result<Statement, ChumskyError>;
}

/// Extract a function signature from a parsed body statement.
///
/// The function text parser calls this after `parse_and_emit` to get the
/// specialized signature when the framework didn't parse one from the header.
///
/// Default implementation returns `None` (framework uses its own parsed signature).
/// Override for languages whose function body types carry signature information
/// (e.g., DiGraph ports → params, yields → return types).
///
/// Generated by `#[derive(HasParser)]` with a default `None` implementation.
/// Dialect authors override it manually for projected function body types.
pub trait ExtractSignature<L: Dialect = Self>: Dialect {
    fn extract_signature(
        _stmt: Statement,
        _stage: &StageInfo<L>,
    ) -> Option<Signature<L::Type>> {
        None
    }
}

/// Marker trait for dialects whose `HasParser::Output` directly implements `EmitIR`.
///
/// Provides a blanket `ParseEmit` impl. Works for dialects that satisfy the
/// `for<'t> <L as HasParser<'t>>::Output: EmitIR<L>` bound. For dialects
/// using `#[derive(HasParser)]`, prefer the derive-generated `ParseEmit` impl
/// (path 1) which handles this automatically.
pub trait SimpleParseEmit: Dialect {}

impl<L> ParseEmit<L> for L
where
    L: SimpleParseEmit,
    for<'t> L: HasParser<'t>,
    for<'t> <L as HasParser<'t>>::Output: EmitIR<L, Output = Statement>,
{
    fn parse_and_emit(
        input: &str,
        ctx: &mut EmitContext<'_, L>,
    ) -> Result<Statement, ChumskyError> {
        let ast = parse_ast::<L>(input)?;
        ast.emit(ctx).map_err(ChumskyError::Emit)
    }
}

impl<L: SimpleParseEmit> ExtractSignature for L {}
