from .lattice import NotConst, PartialLambda, PartialTuple, Unknown, Value

class _ElemVisitor:
    def is_subseteq_Value(self, other: Value) -> bool: ...
    def is_subseteq_NotConst(self, other: NotConst) -> bool: ...
    def is_subseteq_Unknown(self, other: Unknown) -> bool: ...
    def is_subseteq_PartialTuple(self, other: PartialTuple) -> bool: ...
    def is_subseteq_PartialLambda(self, other: PartialLambda) -> bool: ...
